#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'gradingStudents' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts INTEGER_ARRAY grades as parameter.
#

n=int(input())
for x in range (n):
    grade=int(input())
    if grade >= 38:
        mod = grade % 5
        if mod >= 3:
            grade += (5 - mod)
    print(grade)
